name: Node CI

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v1
      - run: echo ${{github.ref}}
      - name: print env information
        run: |
          echo ${{github.event.repository.owner}}
          ls -la
          pwd
      - name: Build
        run: |
          export NODE_OPTIONS=--max-old-space-size=10230
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
          echo $PATH
          yarn
          yarn build
          ls -la
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/

